// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MediaPlannerCore.Data.Context;

namespace MediaPlannerCore.Data.Migrations
{
    [DbContext(typeof(MediaPlannerCoreContext))]
    [Migration("20191225110809_Initial Tables")]
    partial class InitialTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MediaPlannerCore.Model.Models.Ad", b =>
                {
                    b.Property<int>("AdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("AdBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AdContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AdEndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AdSetId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AdStartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("RedirectUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdId");

                    b.HasIndex("AdSetId")
                        .IsUnique()
                        .HasFilter("[AdSetId] IS NOT NULL");

                    b.HasIndex("CampaignId");

                    b.ToTable("Ad");
                });

            modelBuilder.Entity("MediaPlannerCore.Model.Models.AdSet", b =>
                {
                    b.Property<int>("AdSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int?>("MediaChannelId")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("AdSetId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("MediaChannelId");

                    b.HasIndex("SupplierId");

                    b.ToTable("AdSet");
                });

            modelBuilder.Entity("MediaPlannerCore.Model.Models.Campaign", b =>
                {
                    b.Property<int>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CampaignName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("CampaignId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CountryId");

                    b.ToTable("Campaign");
                });

            modelBuilder.Entity("MediaPlannerCore.Model.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("MediaPlannerCore.Model.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("MediaPlannerCore.Model.Models.MediaChannel", b =>
                {
                    b.Property<int>("MediaChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MediaChannelName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MediaChannelId");

                    b.ToTable("MediaChannel");
                });

            modelBuilder.Entity("MediaPlannerCore.Model.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MediaChannelId")
                        .HasColumnType("int");

                    b.Property<string>("SupplierName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.HasIndex("MediaChannelId");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("MediaPlannerCore.Model.Models.Ad", b =>
                {
                    b.HasOne("MediaPlannerCore.Model.Models.AdSet", "AdSet")
                        .WithOne("Ad")
                        .HasForeignKey("MediaPlannerCore.Model.Models.Ad", "AdSetId");

                    b.HasOne("MediaPlannerCore.Model.Models.Campaign", "Campaign")
                        .WithMany("Ad")
                        .HasForeignKey("CampaignId");
                });

            modelBuilder.Entity("MediaPlannerCore.Model.Models.AdSet", b =>
                {
                    b.HasOne("MediaPlannerCore.Model.Models.Campaign", "Campaign")
                        .WithMany("AdSet")
                        .HasForeignKey("CampaignId");

                    b.HasOne("MediaPlannerCore.Model.Models.MediaChannel", "MediaChannel")
                        .WithMany("AdSet")
                        .HasForeignKey("MediaChannelId");

                    b.HasOne("MediaPlannerCore.Model.Models.Supplier", "Supplier")
                        .WithMany("AdSet")
                        .HasForeignKey("SupplierId");
                });

            modelBuilder.Entity("MediaPlannerCore.Model.Models.Campaign", b =>
                {
                    b.HasOne("MediaPlannerCore.Model.Models.Client", "Client")
                        .WithMany("Campaigns")
                        .HasForeignKey("ClientId");

                    b.HasOne("MediaPlannerCore.Model.Models.Country", "Country")
                        .WithMany("Campaign")
                        .HasForeignKey("CountryId");
                });

            modelBuilder.Entity("MediaPlannerCore.Model.Models.Supplier", b =>
                {
                    b.HasOne("MediaPlannerCore.Model.Models.MediaChannel", "MediaChannel")
                        .WithMany("Supplier")
                        .HasForeignKey("MediaChannelId");
                });
#pragma warning restore 612, 618
        }
    }
}
